<a href="https://colab.research.google.com/github/edwardoughton/spatial_computing/blob/main/5_01_Intro_To_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intro to Pandas

In this class we will introduce the `pandas` package, and cover a range of basic functions necessary to get started with this very useful and flexible package.

The Python data analysis package `pandas` is widely used for importing, manipulating and exporting datasets in a panel format: https://pandas.pydata.org/

By 'panel format' we mean that `pandas` is based on using dataframes. They allow us to store data as panels in rows and columns. You may have encountered this data structure in R or Matlab. If not, you can think of the approach as similar to how you use a spreadsheet (except with far greater flexibility and power in Python).

Later, we will work with an affiliated sub-library `geopandas` that specifically enables you to work with geospatial data.

**For the purposes of learning as much as possible in this class, please begin by turning off code completions (see Tools/Settings/Editor/untick automatically trigger code completions).**

## Importing data into Colab

To begin, we first need to import data into our colab notebook. This will be a common first step before you begin quantitatively analyzing data.

There are actually multiple ways:

*   Local upload from current machine.
*   Go to the file menu and mount your Google Drive.
*   Upload from Google Sheets.
*   Straight download from a Uniform Resource Locator (URL).

We will begin with loading from your local machine. First, download from the MyMason Blackboard site the .csv file `virginia.csv`.

Now run the code cell below, select the data and import.

In [1]:
# Example: Loading data from a local machine
from google.colab import files
uploaded = files.upload()

Saving virginia.csv to virginia.csv

Now we have this Comma Separated Value (.csv) file in our colab memory, we can import this data using pandas.

We will import the package as normal, e.g., `import pandas`.

To simplify the calling of this package, we can specify a shortened version of the name using the in-built Python command `as`. It is common to load `pandas` in short form as `pd`.

Moreover, once loaded we can import the file using the `.read_csv()` function, and then passing the filepath or filename. As we have loaded this data already into our memory, calling via the filename is sufficient to find the data file.

In [32]:
# Example: Importing the pandas package
import pandas as pd

# Example: Importing the .csv file via `.read_csv()`
df = pd.read_csv('virginia.csv')

# Example: Viewing our dataframe
df

,GID_0,NAME_0,GID_1,NAME_1,NL_NAME_1,GID_2,NAME_2,VARNAME_2,NL_NAME_2,TYPE_2,ENGTYPE_2,CC_2,HASC_2,area_m2
0,USA,United States,USA.47_1,Virginia,NaN,USA.47.1_1,Accomack,NaN,NaN,County,County,NaN,US.VA.AC,1.237202e+09
1,USA,United States,USA.47_1,Virginia,NaN,USA.47.2_1,Albemarle,NaN,NaN,County,County,NaN,US.VA.AB,1.874287e+09
2,USA,United States,USA.47_1,Virginia,NaN,USA.47.3_1,Alexandria,NaN,NaN,Independent City,Independent City,NaN,US.VA.AX,4.057266e+07
3,USA,United States,USA.47_1,Virginia,NaN,USA.47.4_1,Alleghany,NaN,NaN,County,County,NaN,US.VA.AL,1.155584e+09
4,USA,United States,USA.47_1,Virginia,NaN,USA.47.5_1,Amelia,NaN,NaN,County,County,NaN,US.VA.AI,9.540803e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,USA,United States,USA.47_1,Virginia,NaN,USA.47.130_1,Winchester,NaN,NaN,Independent City,Independent City,NaN,US.VA.WH,2.348413e+07
130,USA,United States,USA.47_1,Virginia,NaN,USA.47.131_1,Wise,NaN,NaN,County,County,NaN,US.VA.WI,1.046817e+09
131,USA,United States,USA.47_1,Virginia,NaN,USA.47.132_1,Wythe,NaN,NaN,County,County,NaN,US.VA.WY,1.202077e+09
132,USA,United States,USA.47_1,Virginia,NaN,USA.47.133_1,York,NaN,NaN,County,County,NaN,US.VA.YO,2.821160e+08
133,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Task

* Save your .csv file as an excel file (e.g., .xlsx) (Hint: read the documentation).
* Work out how to import this file using `pandas` (e.g., using `.read_excel()`).

In [ ]:
# Insert your attempt here

## Manipulating our dataframe

Now we have our data loaded into the memory of our colab notebook, we can begin exploring.

You can examine the top *n* rows of your dataframe using the `.head()` function.

In [16]:
# Example: Inspecting the head of a dataframe (n=5 by default)
# Note: Try specify the number of desired rows
df.head()

,GID_0,NAME_0,GID_1,NAME_1,NL_NAME_1,GID_2,NAME_2,VARNAME_2,NL_NAME_2,TYPE_2,ENGTYPE_2,CC_2,HASC_2,area_m2
0,USA,United States,USA.47_1,Virginia,NaN,USA.47.1_1,Accomack,NaN,NaN,County,County,NaN,US.VA.AC,1.237202e+09
1,USA,United States,USA.47_1,Virginia,NaN,USA.47.2_1,Albemarle,NaN,NaN,County,County,NaN,US.VA.AB,1.874287e+09
2,USA,United States,USA.47_1,Virginia,NaN,USA.47.3_1,Alexandria,NaN,NaN,Independent City,Independent City,NaN,US.VA.AX,4.057266e+07
3,USA,United States,USA.47_1,Virginia,NaN,USA.47.4_1,Alleghany,NaN,NaN,County,County,NaN,US.VA.AL,1.155584e+09
4,USA,United States,USA.47_1,Virginia,NaN,USA.47.5_1,Amelia,NaN,NaN,County,County,NaN,US.VA.AI,9.540803e+08

Equally, you can inspect the tail of your dataframe using the `.tail()` function.

In [ ]:
# Example: Inspecting the tail of a dataframe (n=5 by default)
# Note: Try specify the number of desired rows
df.tail()

,GID_0,NAME_0,GID_1,NAME_1,NL_NAME_1,GID_2,NAME_2,VARNAME_2,NL_NAME_2,TYPE_2,ENGTYPE_2,CC_2,HASC_2,area_m2
129,USA,United States,USA.47_1,Virginia,NaN,USA.47.130_1,Winchester,NaN,NaN,Independent City,Independent City,NaN,US.VA.WH,2.348413e+07
130,USA,United States,USA.47_1,Virginia,NaN,USA.47.131_1,Wise,NaN,NaN,County,County,NaN,US.VA.WI,1.046817e+09
131,USA,United States,USA.47_1,Virginia,NaN,USA.47.132_1,Wythe,NaN,NaN,County,County,NaN,US.VA.WY,1.202077e+09
132,USA,United States,USA.47_1,Virginia,NaN,USA.47.133_1,York,NaN,NaN,County,County,NaN,US.VA.YO,2.821160e+08
133,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Before we get started with summarizing the data, it is useful to understand the metadata associated with the dataframe.

We can do this via the `.info()` function, which reports column names, non-null counts and the data type (Dtype).

In [15]:
# Example: Associated metadata for our dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   GID_0      133 non-null    object
 1   NAME_0     133 non-null    object
 2   GID_1      133 non-null    object
 3   NAME_1     133 non-null    object
 4   NL_NAME_1  0 non-null      float64
 5   GID_2      133 non-null    object
 6   NAME_2     133 non-null    object
 7   VARNAME_2  0 non-null      float64
 8   NL_NAME_2  0 non-null      float64
 9   TYPE_2     133 non-null    object
 10  ENGTYPE_2  133 non-null    object
 11  CC_2       0 non-null      float64
 12  HASC_2     133 non-null    object
 13  area_m2    130 non-null    float64
dtypes: float64(5), object(9)
memory usage: 14.8+ KB

Moreover, we can find out how many rows and columns we have by utilizing the `.shape()` function.

In [ ]:
# Example: Obtaining the dataframe row and column count
df.shape

(134, 14)

Additionally, we can print the column dataframe names as follows, using the `.columns` function.

This is handy when writing a normal `python` script, without the easy functionality of a notebook.

In [8]:
# Example: Viewing a summary of the dataframe column names
df.columns

Index(['GID_0', 'NAME_0', 'GID_1', 'NAME_1', 'NL_NAME_1', 'GID_2', 'NAME_2',
       'VARNAME_2', 'NL_NAME_2', 'TYPE_2', 'ENGTYPE_2', 'CC_2', 'HASC_2',
       'area_m2'],
      dtype='object')

Equally, we can view the dataframe index values using the `.index` function.

The index is an essential piece of information in both a `pandas` series and dataframe, as it provides a label ID for each row. Thus, if we desire, we can uniquely identify and access individual row elements, values or subsets of the data.

In [ ]:
# Example: Viewing a summary of the dataframe index
df.index

RangeIndex(start=0, stop=134, step=1)

To select a row, we can use the `.loc[]` function to index, and then pass our index value.

We can do this for the zero index location as follows.

In [12]:
# Example: We can select the first row in index location zero
# Note: Try manually subset other rows
df.loc[0]

GID_0                  USA
NAME_0       United States
GID_1             USA.47_1
NAME_1            Virginia
NL_NAME_1              NaN
GID_2           USA.47.1_1
NAME_2            Accomack
VARNAME_2              NaN
NL_NAME_2              NaN
TYPE_2              County
ENGTYPE_2           County
CC_2                   NaN
HASC_2            US.VA.AC
area_m2       1237202429.0
Name: 0, dtype: object

Often we might have to deal with missing data.

There are multiple ways, but here a few important ones are outlined

We can query a dataframe to check if the values are `NaN` or not using the `.isnull()` function.

This returns a True/False dataframe indicating missing values.

Note: `NaN` stands for "Not a Number" and is indicative of missing or undefined data (e.g., null values).

In [13]:
# Example: Checking a dataframe for missing data
df.isnull()

,GID_0,NAME_0,GID_1,NAME_1,NL_NAME_1,GID_2,NAME_2,VARNAME_2,NL_NAME_2,TYPE_2,ENGTYPE_2,CC_2,HASC_2,area_m2
0,False,False,False,False,True,False,False,True,True,False,False,True,False,False
1,False,False,False,False,True,False,False,True,True,False,False,True,False,False
2,False,False,False,False,True,False,False,True,True,False,False,True,False,False
3,False,False,False,False,True,False,False,True,True,False,False,True,False,False
4,False,False,False,False,True,False,False,True,True,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,False,False,False,False,True,False,False,True,True,False,False,True,False,False
130,False,False,False,False,True,False,False,True,True,False,False,True,False,False
131,False,False,False,False,True,False,False,True,True,False,False,True,False,False
132,False,False,False,False,True,False,False,True,True,False,False,True,False,False
133,True,True,True,True,True,True,True,True,True,True,True,True,True,True

You can also just drop all rows with missing data via the `.dropna()` function.

As we have entire columns of missing data in our dataframe, this will mean all rows are dropped.

In [17]:
# Example: Dropping rows with missing data (e.g., NaN)
df.dropna()

Empty DataFrame
Columns: [GID_0, NAME_0, GID_1, NAME_1, NL_NAME_1, GID_2, NAME_2, VARNAME_2, NL_NAME_2, TYPE_2, ENGTYPE_2, CC_2, HASC_2, area_m2]
Index: []

If you want to avoid this, we could take a subset of columns which we know are generally complete, using a double set of index parentheses (`[[]]`) containing the column names we want to keep.

In `pandas`, we can subset columns of interest like so.

In [18]:
# Example: Subsetting columns of interest
df[['NAME_0', 'NAME_2', 'area_m2']]

            NAME_0      NAME_2       area_m2
0    United States    Accomack  1.237202e+09
1    United States   Albemarle  1.874287e+09
2    United States  Alexandria  4.057266e+07
3    United States   Alleghany  1.155584e+09
4    United States      Amelia  9.540803e+08
..             ...         ...           ...
129  United States  Winchester  2.348413e+07
130  United States        Wise  1.046817e+09
131  United States       Wythe  1.202077e+09
132  United States        York  2.821160e+08
133            NaN         NaN           NaN

[134 rows x 3 columns]

Now we can retry our `.dropna()` function, like so.

We will reallocate the columns we want to subset to a new dataframe called `subset`.

In [20]:
# Example: Subset our dataframe and drop rows with missing data

# Note: We subset our data and allocate to new dataframe variable name
subset = df[['NAME_0', 'NAME_2', 'area_m2']]

# Drop rows with missing data
subset = subset.dropna()
print("Original df length is {}".format(len(df)))
print("New df length is {}".format(len(subset)))

Original df length is 134
New df length is 130

Task

Subset the GID_0, NAME_0, GID_1, NAME_1, GID_2 and NAME_2 columns to a new dataframe called `subset2`.

Drop rows with missing data.

Check the length of the original and final dataframes to inspect the differences.

In [ ]:
# Insert your attempt here

You could choose to fill missing data points with values of your choice, via the `.fillna()` function.

Just be careful using this, **you do not want to arbitrarily insert values of your own choice into a statistical distribution!**

In [21]:
# Example: Filling missing values with a desired value
df_filled = df.fillna(0)
df_filled

,GID_0,NAME_0,GID_1,NAME_1,NL_NAME_1,GID_2,NAME_2,VARNAME_2,NL_NAME_2,TYPE_2,ENGTYPE_2,CC_2,HASC_2,area_m2
0,USA,United States,USA.47_1,Virginia,0.0,USA.47.1_1,Accomack,0.0,0.0,County,County,0.0,US.VA.AC,1.237202e+09
1,USA,United States,USA.47_1,Virginia,0.0,USA.47.2_1,Albemarle,0.0,0.0,County,County,0.0,US.VA.AB,1.874287e+09
2,USA,United States,USA.47_1,Virginia,0.0,USA.47.3_1,Alexandria,0.0,0.0,Independent City,Independent City,0.0,US.VA.AX,4.057266e+07
3,USA,United States,USA.47_1,Virginia,0.0,USA.47.4_1,Alleghany,0.0,0.0,County,County,0.0,US.VA.AL,1.155584e+09
4,USA,United States,USA.47_1,Virginia,0.0,USA.47.5_1,Amelia,0.0,0.0,County,County,0.0,US.VA.AI,9.540803e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,USA,United States,USA.47_1,Virginia,0.0,USA.47.130_1,Winchester,0.0,0.0,Independent City,Independent City,0.0,US.VA.WH,2.348413e+07
130,USA,United States,USA.47_1,Virginia,0.0,USA.47.131_1,Wise,0.0,0.0,County,County,0.0,US.VA.WI,1.046817e+09
131,USA,United States,USA.47_1,Virginia,0.0,USA.47.132_1,Wythe,0.0,0.0,County,County,0.0,US.VA.WY,1.202077e+09
132,USA,United States,USA.47_1,Virginia,0.0,USA.47.133_1,York,0.0,0.0,County,County,0.0,US.VA.YO,2.821160e+08
133,0,0,0,0,0.0,0,0,0.0,0.0,0,0,0.0,0,0.000000e+00

We can obtain summary statistics for a specific column by indexing with the column name, as follows.

In [22]:
# Example: Indexing by column name
df['area_m2'].sum()

96496076219.0

We have a variety of statistical functions at our finger tips.

In [23]:
# Example: Summarizing a column
print(df['area_m2'].mean())
print(df['area_m2'].median())
print(df['area_m2'].min())
print(df['area_m2'].max())

742277509.3769231
770881080.0
5121049.0
2135881041.0

You can also summarize the unique values.

In [ ]:
# Example: Unique values for Virginia area names
df['NAME_2'].unique()

array(['Accomack', 'Albemarle', 'Alexandria', 'Alleghany', 'Amelia',
       'Amherst', 'Appomattox', 'Arlington', 'Augusta', 'Bath', 'Bedford',
       'Bedford City', 'Bland', 'Botetourt', 'Bristol', 'Brunswick',
       'Buchanan', 'Buckingham', 'Buena Vista', 'Campbell', 'Caroline',
       'Carroll', 'Charles City', 'Charlotte', 'Charlottesville',
       'Chesapeake', 'Chesterfield', 'Clarke', 'Clifton Forge City',
       'Colonial Heights', 'Covington', 'Craig', 'Culpeper', 'Cumberland',
       'Danville', 'Dickenson', 'Dinwiddie', 'Emporia', 'Essex',
       'Fairfax', 'Fairfax City', 'Falls Church', 'Fauquier', 'Floyd',
       'Fluvanna', 'Franklin', 'Frederick', 'Fredericksburg', 'Galax',
       'Giles', 'Gloucester', 'Goochland', 'Grayson', 'Greene',
       'Greensville', 'Halifax', 'Hampton', 'Hanover', 'Harrisonburg',
       'Henrico', 'Henry', 'Highland', 'Hopewell', 'Isle of Wight',
       'James City', 'King and Queen', 'King George', 'King William',
       'Lancaster', 'Lee', 'Lexington', 'Loudoun', 'Louisa', 'Lunenburg',
       'Lynchburg', 'Madison', 'Manassas', 'Manassas Park',
       'Martinsville', 'Mathews', 'Mecklenburg', 'Middlesex',
       'Montgomery', 'Nelson', 'New Kent', 'Newport News', 'Norfolk',
       'Northampton', 'Northumberland', 'Norton', 'Nottoway', 'Orange',
       'Page', 'Patrick', 'Petersburg', 'Pittsylvania', 'Poquoson',
       'Portsmouth', 'Powhatan', 'Prince Edward', 'Prince George',
       'Prince William', 'Pulaski', 'Radford', 'Rappahannock', 'Richmond',
       'Roanoke', 'Roanoke City', 'Rockbridge', 'Rockingham', 'Russell',
       'Salem', 'Scott', 'Shenandoah', 'Smyth', 'Southampton',
       'Spotsylvania', 'Stafford', 'Staunton', 'Suffolk', 'Surry',
       'Sussex', 'Tazewell', 'Virginia Beach', 'Warren', 'Washington',
       'Waynesboro', 'Westmoreland', 'Williamsburg', 'Winchester', 'Wise',
       'Wythe', 'York', nan], dtype=object)

In [24]:
# Example: Unique values for Virginia area names
df['GID_0'].unique()

array(['USA', nan], dtype=object)

Importantly, we can group on certain columns and summarize, by first using the `.groupby()` function, followed by our statistical function name, such as `.mean()`.

In [31]:
# Example: Groupby and summarize for the state of Virginia
df = df[['NAME_1','area_m2']]
df.groupby('NAME_1').mean()

               area_m2
NAME_1
Virginia  7.422775e+08

In [34]:
# Example: Groupby and summarize for adminstrative type
df = pd.read_csv('virginia.csv')
df = df[['TYPE_2','area_m2']]
df.groupby('TYPE_2').mean()

                       area_m2
TYPE_2
City              1.903495e+07
County            1.005642e+09
Independent City  1.336368e+08

It is possible for us to create new variables, we just need to specify the dataframe and new column name on the left hand side.

In [35]:
# Example: Creating a new variable
df['my_new_variable'] = 'my_new_value'
df

               TYPE_2       area_m2 my_new_variable
0              County  1.237202e+09    my_new_value
1              County  1.874287e+09    my_new_value
2    Independent City  4.057266e+07    my_new_value
3              County  1.155584e+09    my_new_value
4              County  9.540803e+08    my_new_value
..                ...           ...             ...
129  Independent City  2.348413e+07    my_new_value
130            County  1.046817e+09    my_new_value
131            County  1.202077e+09    my_new_value
132            County  2.821160e+08    my_new_value
133               NaN           NaN    my_new_value

[134 rows x 3 columns]

Task

Can you create a new variable, converting the area in square meters into square kilometers?

In [ ]:
# Insert your attempt here

Now try find the mean, median, minimum and maximum values for the area based on the TYPE_2 column (in square kilometers).

In [ ]:
# Insert your attempt here

Subset the GID_0, NAME_0, GID_1, NAME_1, GID_2 and NAME_2 columns to a new dataframe called subset2.

Now obtain the unique rows. You can use Google/StackOverflow.

In [ ]:
# Insert your attempt here

## Exporting data

One of the most handy functions within pandas is being able to quickly export your data to a desired format.

For example, we can use the `.to_csv()` function to export to a .csv file.

Once you have run the cell below, look in the colab file browser for your file, and then download to your local machine to inspect.

In [37]:
# Example: Exporting dataframe data to a .csv
df = pd.read_csv('virginia.csv')
output = df[['NAME_0', 'NAME_2', 'area_m2']]
output.to_csv('output.csv', index=False)

Task

* Export the original full dataframe to an excel .xlsx format.
* Subset the original dataframe on the GID_2 and area columns. Export to a .csv file.
* Summarize the area dataframe on the TYPE_2 column, and export as a .xlsx file.

In [ ]:
# Insert your attempt here